# Generated by Django 4.1.5 on 2023-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Terminal', 'Terminal'), ('Django', 'Django The Great')], max_length=40)),
                ('rate_understanding', models.PositiveIntegerField()),
                ('revised_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
